Better use declared usleep_range instead of usleep
kernel/msm-3.18/drivers/leds/leds-aw2013.c: In function 'aw_2013_check_chipid':
kernel/msm-3.18/drivers/leds/leds-aw2013.c:389:2: error: implicit declaration of function 'usleep' [-Werror=implicit-function-declaration]
  usleep(AW_LED_RESET_DELAY);